spring:
  application:
    name: kotlin-spring-playground

  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true

  datasource:
    url: jdbc:postgresql://localhost:5432/tidal_artists
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariPool-1

  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:config/liquibase/changelog-master.xml
    enabled: true

tidal:
  client-id: # env vars
  client-secret: # env vars

outbox:
  publisher:
    cloudevent-source: "com.hvs.kotlinspringplayground"
    polling-rate: PT10S
  database: postgres

rabbitmq:
  exchange: "music_monitor"
  queue: "release"
  routing-key: "release_routing_key"
  delivery-timeout: 1