spring:
  application:
    name: music-release-notifier-core
  security:
    oauth2:
      client:
#        registration:
#          keycloak:
#            client-id: music-release-notifier-client-credentials
#            client-secret: HBz2L6Apo6g2w1ohVM2S3wul6Dv8zH85
#            scope:
#              - profile
#              - openid
#              - email
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/music-release-notifier/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://localhost:5432/music-release-notifier
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000 # 5 seconds
      connection-test-query: SELECT 1
      pool-name: HikariPool-1
  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:config/liquibase/changelog-master.xml
    enabled: true

cors:
  allowed-origins: http://localhost:4201

rabbitmq:
  exchange: "music_monitor"
  queue: "release"
  routing-key: "release_routing_key"
  delivery-timeout: 1